/* istanbul ignore file */
import type { Meta, StoryObj } from '@storybook/react';
import { Icon, IconSprite, SPRITE_ICONS } from '@lumia/icons';

const registryIcons = [
  { name: 'home', label: 'Home' },
  { name: 'user', label: 'User' },
  { name: 'sparkle', label: 'Sparkle (custom)' },
  { name: 'chat-bubble', label: 'Chat bubble (custom)' },
];

const meta: Meta<typeof Icon> = {
  title: 'Foundations/Icons',
  component: Icon,
  tags: ['autodocs'],
  argTypes: {
    name: {
      control: 'text',
      description: 'Icon name from registry (sprite or SVGR)',
    },
    size: {
      control: 'select',
      options: ['sm', 'md', 'lg'],
      description: 'Size preset or custom pixel value',
    },
    color: {
      control: 'select',
      options: ['default', 'muted', 'primary', 'danger'],
      description: 'Color preset or custom CSS value',
    },
    title: {
      control: 'text',
      description: 'Accessible title for screen readers',
    },
  },
  args: {
    name: 'info',
    size: 'md',
    color: 'default',
  },
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: `
The unified \`<Icon>\` component provides a single API for all icons, 
automatically choosing the optimal rendering path (sprite vs SVGR).

## Usage

\`\`\`tsx
import { Icon } from '@lumia/icons';

// Basic usage
<Icon name="info" />

// With size preset
<Icon name="check" size="lg" />

// With color preset
<Icon name="alert" color="danger" />

// With accessible title
<Icon name="warning" title="Warning message" />
\`\`\`

## Size Presets
- \`sm\` = 16px
- \`md\` = 24px (default)
- \`lg\` = 32px

## Color Presets
- \`default\` → text-foreground
- \`muted\` → text-muted-foreground
- \`primary\` → text-primary
- \`danger\` → text-destructive
        `,
      },
    },
  },
  decorators: [
    (Story) => (
      <>
        <IconSprite />
        <Story />
      </>
    ),
  ],
};

export default meta;
type Story = StoryObj<typeof Icon>;

export const Default: Story = {
  args: {
    name: 'info',
    size: 'md',
    color: 'primary',
  },
};

export const Registry: Story = {
  render: (args) => (
    <div className="grid grid-cols-2 gap-6 bg-background p-6 sm:grid-cols-4">
      {registryIcons.map((icon) => (
        <div key={icon.name} className="flex flex-col items-center gap-3">
          <Icon {...args} name={icon.name} />
          <span className="text-sm text-foreground">{icon.label}</span>
        </div>
      ))}
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Icons are registered in memory and can be referenced by name anywhere in the system. Custom icons generated by the CLI appear alongside curated Lucide icons.',
      },
    },
  },
};

export const SizePresets: Story = {
  render: () => (
    <div className="flex items-end gap-6 bg-background p-6">
      <div className="flex flex-col items-center gap-2">
        <Icon name="sparkle" size="sm" color="primary" />
        <span className="text-xs text-muted-foreground">sm (16px)</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="sparkle" size="md" color="primary" />
        <span className="text-xs text-muted-foreground">md (24px)</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="sparkle" size="lg" color="primary" />
        <span className="text-xs text-muted-foreground">lg (32px)</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="sparkle" size={48} color="primary" />
        <span className="text-xs text-muted-foreground">48px (custom)</span>
      </div>
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Size can be a preset (`sm`, `md`, `lg`) or a custom number in pixels.',
      },
    },
  },
};

export const ColorPresets: Story = {
  render: () => (
    <div className="flex items-center gap-6 bg-background p-6">
      <div className="flex flex-col items-center gap-2">
        <Icon name="info" size="lg" color="default" />
        <span className="text-xs text-muted-foreground">default</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="info" size="lg" color="muted" />
        <span className="text-xs text-muted-foreground">muted</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="check" size="lg" color="primary" />
        <span className="text-xs text-muted-foreground">primary</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="alert" size="lg" color="danger" />
        <span className="text-xs text-muted-foreground">danger</span>
      </div>
      <div className="flex flex-col items-center gap-2">
        <Icon name="info" size="lg" color="#ff5500" />
        <span className="text-xs text-muted-foreground">#ff5500</span>
      </div>
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Color presets map to semantic CSS classes. Custom colors are applied as inline styles.',
      },
    },
  },
};

export const SpriteIcons: Story = {
  render: () => (
    <div className="flex flex-col gap-4 bg-background p-6">
      <p className="text-sm text-muted-foreground">
        These icons automatically use &lt;use href&gt; for better performance:
      </p>
      <div className="grid grid-cols-3 gap-4 sm:grid-cols-5">
        {SPRITE_ICONS.map((name) => (
          <div key={name} className="flex flex-col items-center gap-2">
            <Icon name={name} size="lg" color="primary" />
            <span className="text-xs text-muted-foreground">{name}</span>
          </div>
        ))}
      </div>
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story:
          'Sprite icons are hot-path icons rendered via `<use href="#icon-*">` for optimal performance.',
      },
    },
  },
};

export const WithAccessibleTitle: Story = {
  render: () => (
    <div className="flex flex-col gap-6 bg-background p-6">
      <div>
        <h3 className="mb-3 text-sm font-medium text-foreground">
          Decorative Icons (hidden from screen readers)
        </h3>
        <div className="flex items-center gap-4">
          <div className="flex flex-col items-center gap-2">
            <Icon name="check" size="lg" color="primary" />
            <code className="text-xs text-muted-foreground">
              aria-hidden, focusable=false
            </code>
          </div>
          <div className="flex flex-col items-center gap-2">
            <Icon name="info" size="lg" color="muted" />
            <code className="text-xs text-muted-foreground">No title prop</code>
          </div>
        </div>
      </div>
      <div>
        <h3 className="mb-3 text-sm font-medium text-foreground">
          Informative Icons (announced by screen readers)
        </h3>
        <div className="flex items-center gap-4">
          <div className="flex flex-col items-center gap-2">
            <Icon
              name="alert"
              size="lg"
              color="danger"
              title="Warning: Action required"
            />
            <code className="text-xs text-muted-foreground">
              role=img, aria-labelledby
            </code>
          </div>
          <div className="flex flex-col items-center gap-2">
            <Icon
              name="check"
              size="lg"
              color="primary"
              title="Success: Changes saved"
            />
            <code className="text-xs text-muted-foreground">
              With title prop
            </code>
          </div>
        </div>
      </div>
      <p className="text-xs text-muted-foreground">
        Open DevTools → Elements to verify: decorative icons have{' '}
        <code>aria-hidden=&quot;true&quot;</code> and{' '}
        <code>focusable=&quot;false&quot;</code>; informative icons have{' '}
        <code>&lt;title&gt;</code> and <code>role=&quot;img&quot;</code>.
      </p>
    </div>
  ),
  parameters: {
    docs: {
      description: {
        story: `
**Decorative icons** are purely visual and should be hidden from assistive technologies:
\`\`\`tsx
<Icon name="check" /> // aria-hidden="true" focusable="false"
\`\`\`

**Informative icons** convey meaning and need accessible labels:
\`\`\`tsx
<Icon name="alert" title="Warning: Action required" />
// role="img" aria-labelledby="icon-title-alert"
\`\`\`
        `,
      },
    },
  },
};

